# Trigger on pipeline deploy for trunk runs
name: deploy notification

on:
  deployment_status:

jobs:
  on-deploy:
    runs-on: ubuntu-latest
    # if: contains(fromJSON('["failure","success", "waiting"]'), github.event.deployment_status.state)
    if: github.event.deployment_status.state == 'success' && github.event.deployment.environment == 'production' && github.event.sender.id == 35613825 && contains(github.event.deployment_status.target_url, 'workflows-test')
    steps:
      - name: "${{ github.event_name }}"
        run: echo '${{ toJSON(github) }}'
      - name: env vars
        run: set
      - name: "output event"
        run: |
          echo "Deployed to: ${{ github.event.deployment_status.environment }}"
          echo "Deployed outcome: ${{ github.event.deployment_status.state }}"
      - name: summary
        run: |
          echo "# Trigger Summary" >> $GITHUB_STEP_SUMMARY
          echo "Event Name: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
          echo "Event Type: ${{ github.event.workflow_run.event }}" >> $GITHUB_STEP_SUMMARY
          echo "Ref Name: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "Ref Type: ${{ github.ref_type }}" >> $GITHUB_STEP_SUMMARY
          echo "Deployed to: ${{ github.event.deployment_status.environment }}" >> $GITHUB_STEP_SUMMARY
          echo "Deployed State: ${{ github.event.deployment_status.state }}" >> $GITHUB_STEP_SUMMARY
  on-deploy-skipped:
    runs-on: ubuntu-latest
    if: contains(fromJSON('["failure","success", "waiting"]'), github.event.deployment_status.state) == false
    steps:
      - name: "${{ github.event_name }}"
        run: echo '${{ toJSON(github) }}'
      - name: env vars
        run: set
      - name: "output event"
        run: |
          echo "Deployed to: ${{ github.event.deployment_status.environment }}"
          echo "Deployed outcome: ${{ github.event.deployment_status.state }}"
      - name: summary
        run: |
          echo "# Trigger Summary" >> $GITHUB_STEP_SUMMARY
          echo "Event Name: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
          echo "Event Type: ${{ github.event.workflow_run.event }}" >> $GITHUB_STEP_SUMMARY
          echo "Ref Name: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "Ref Type: ${{ github.ref_type }}" >> $GITHUB_STEP_SUMMARY
          echo "Deployed to: ${{ github.event.deployment_status.environment }}" >> $GITHUB_STEP_SUMMARY
          echo "Deployed State: ${{ github.event.deployment_status.state }}" >> $GITHUB_STEP_SUMMARY
      - name: fail
        run: exit 1
